name: server
description: A Rest Api with dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  sqlite3: ^3.1.1
  http: ^1.6.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
